language: python
python:
- '3.6'
install:
- pip install ansible>=2.4.0 molecule apache-libcloud pycrypto
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: Ywu51Y/f5sTbMs2s7tOmU+9Woxer+njKVVsemFmY7TKRdo8ql47k+Ib6XTOyVLdoiDPqOhHaWaP6MNktRb5fQZjXjvn3nPQD/Sj1E5Et8RHhR3wJo7q0qrZ6Nsy5VVPxJznND1O7jlG6xVzkBxESEBInN5qLHqwmz+qd+ABMzFoTslDtmjC0sV1Gmd++HzFEhMRWRWAqX68P+IelW7jNInZ/qgtfpTLjM2SYUlkqQXmvVrMYJSnsw74sQmvZ+N5hILvFTVeUcHcMru0OhApABMD/hU7il+2r/Yo5N2zcgHtzwFHixk9XmWC7lSIY71XtpAOiqqRsiQ+dY1nvub8ylsX8NzMTpkFmRONXlbRzhMjq2hvWMYeg1DhMlbCBC7a4znaR2Bw1Fmh9Pj/h2oKUPJK4mjiksrR9Qg0175A/5p+GxnVzZ04aujB+kvMfyVjmmH3UJSZT2rrBIfh0sMLTpvk6NrakJ2XfgvETRurUaxJGNSsU3Fl/8jNiFpLY9FXP2rQzN9brYxe5Qnq6NA7AN8vxYX9+JC+L0BeVHBU7fICTq3B7bK7KIFmDjq8sDhEHnnrfLnewvJwFRyOUyTV76aJbKzttMEjlHifSuyOIenxOD3o15bQ5uaF1P0qKmzvCqCazFrT166+UCoZgWaFh/msgvPTKYHuvV+I/82ZhjrI=
  - secure: KEbKU50RN3ClGkVEA4T+ygYhKsD4Wewe6n98/s4uS6feIelOKL4x26OO7Gf61ZntS1MBJ4PSznebyQB7pulM7kiHrFJmSHp8oXcZCWAdXzkC/+tDE5E03Gxavd+kAc7SwkTU9j246TkXqyi8VPOyscrpgkHrnJvgcBQrvFAblfW6J9TpYAw35irnb5c7cG73OQlYKyX26HF6w8dB1BfOA1o1z9gpHXXxeg2zUKhxiyupMDG0AKphchIBRcZVYR6gez6Cb7y74y+Voe730a8xJitYLNfRttaQaCrjxek7GoQ6FgvNDmiFEbg7/YXYfxLCJWx9PPTCWPeQz08cmwNOHgcsvendJ2odPc9a2GVSFJeV4CDPpdHo0yNfrFa1H7Add+pgPq4ikjDSTukYRmg4pkMZFoOulwoToC7hPB6ly/Uj6/44wL4dxe6nQTfiqtvuCgg+M/db0gYhfXqBYkr7kIfjqxY9nOx86sFrzHfvQEfjbSWdQ03otbfNUs+i1nKlS3W15A5poiReQjzLJcNqsL2SKdh8w+LY7UJt3wZflsEkmNn/Ki182GQwZCkE53+NeFwvLLHS4e5fPFd63TVnLcfMNcgh9XYL7O44eedCIx1xX4HbsercDxu/ZqyDlejjSCh36tvy+KH//QqYR6sHwQZlKgTmjhMapgesJNCGyxs=
  - secure: DjO78h3LhE7z9DrGiFDRay+v5ELRz1Ms4k4GgRzz7F8jpr8fvjePKFx/YO4lVl3IYDXkWcwMLW/wnlKlq3EUiLuTkOa37J7d0riNBBQTeOYFmgPzI/qZGFjESHDzVzGUYmpSbcndQOigFu6uAQEtaryXUK5rMC3ME9WK1TOkv6mkRvaIUmq+0k7/o5FCygUsBuAWBgmVYOQII9I5D5EW+Zlh3TuabCDcwuPt5kHNP510FrsTQKSEtDaa7aDUuI6huGSgH5dG/6XQ74INvMJ0uj8jMouDdckHPLZNTEgdpuW7++zd/jGWOUI7/2d0kuYsMCSOR52ANNg3cpgL6HI56sUGV53C3tEk8GxIJGgLZqti1Zh8NxqN2NNBjA7i6hSZdIiM+Mfcsl3Ci9+Bi0SdHjOrn9GDEPRIIGS3mFO2FCBVarKIWX3n8p3upRYo5sRjr2w7AFCHzb1b6oVWMm7mQ+6ezr0Ai6RfXwwMuREoBK6qzwJq8ZaJ9EtXBK7wiyHcaMoh69oiPYV7uMLsfmDJwnAV4F9K8Edj9czudHEonzwVy9XIRfMgA/I/X0+FKzFVcOVQux0tH81+/b0EaAGgnLU8xo0V+Iu/OOk78GYxWn33lk1I51gsP5agLWc3FYBaseDImB7xP/9ilHTm61G0hxHMROXK/2xgDN6MokH2Ig8=
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
before_install:
- openssl aes-256-cbc -K $encrypted_48923027f180_key -iv $encrypted_48923027f180_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
notifications:
  slack:
    rooms:
      secure: WdT6CCn0mHjzSyd3gjZBsIA42PzL38iQ9pEZE7nsqkzjO421DYZSOJv3+U6fZKC54yzdrI3M9mRw8jHSO4oUyeLVQ/zkD1ttry4anjB/pjXicgmXF1kfWrtJ23p3OzLATfC5k0yTrrggC+F2SI8vO6Gucoc7Fst0e1KPht+aW9TYKU0DKV6yLCAUQ+1H1sjYzkfX4IUvdB/eKvtkWwunf6j/SuzbDdzurCua8PSYIbXSJ6XQhX41h2m3gASmL8HzBQesZmD2kee7I2xi2QQRJPa3SruUpitpeFvoIzes7k/+HYN0bffmAdOzA1rpduQbITIPMH4UolNGQU3UAtMC1kI5XFTMwyHCZgqBPMURggCe35d9Gv0KWOZFBpiA+wetBOV48Dn6e+VUakmF57pkEpM0tzXnJHGjlYpbRnooPw1cGJjpHGEC/hgVzFS47XZ8u+ngXEL27CK8N8VVCOKJ7O7jNkNQPakbD3s0/KXDGAk+D/uDngib7LCFivCDWY6GqO2HmYGK09+rzZtNKePV/w/x99jAlvkdX6nlNOVUCyRzv9SaBuorCeC1HhxM/RORm5CTG8mW2wPi2ItgG7e/1W8Xy1r6/QlLoZEI68P7krYbdFcmMGO0X2YAAxWVXOL/X+emX1RnwZpwctNV2RMaV7XVXjAlhwrvEpb6CC3+foQ=
