language: python
python:
- '3.6'
install:
- pip install ansible>=2.4.0 molecule apache-libcloud pycrypto
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: PZM1IUlnvHekQvXwm8nlaObEcK9yo9PuuEMfN3yCLkK2MlvWiuNmVSGeJG/Yj2dfmONWKXNjtSdP4NqLgkDKtLiWesPobAeYt1FjFhQCMJRl16yi9803svcQ/G5be2UryxZK26+jNAi5Fd/BUN/KXq254KvqHQCKHi6ioX3uxTbPdTXpjOrxViERAGLecd6Xw5faPW7NOwAnOoINPJ+MVoXjz8oyMjUV901pcMnLj7JpHX1ZR+nSxjbzzg9PI07oMNxEPNOpiomYE7eFsv05t+W5xYnAj9FmWAJOeHIk4ZfTJ1+uBYfFCepxt1593tPzJ4nGOlnYGR0bor63qfatajt/jnyLspFzkgYEQBgINfbMApQeX+I1RSjopZv/YQMamA6RLGDvBjKfjCR/FcWQxepgz4wnmGuNp0H/nrbvYS6y0tjdNdt0ZuRp2ZN5ZG0UlOjVEUmOtyHpNOCmWmKZ+1yMxL/JWtoTgH9smovGgfGysv+lJXHfsT25XLjQvO14DTYt5J8t8pQkUvjiEVBAEljPCxw7D677mHUjWoA5cD+HrW1Qj1OnFoS5AdLjeTF+Zq0qdI9fd453Yqt00Rxi3ZLqXqArxKDV3sms5r7a4zE4kr7bgACwic/FGZ0IKbyRX4ZtLpSiCE9xk159ycNHLxvjU3yVP3EpI2NaPiyV6tE=
  - secure: DyjAofLPa6jYl/BV4vJ3vPnH+EGulPEarXYSyszWF0ABMII8PZmdrRnC4MtNrCdv56A2b42ZGKeXL5KSrnnuBmGCdRQyH3DpYqrRgpHIitKewnSmIVlQl6ngpbg5sgAk05tSbLl9a3EJKO8vY75ylKaxNenxNj2SF2+lVP3OqPg9oR4i/WDBlIwAcDn9Fj0KJwEuv/okNa9N6JTKkAGWsTogSbUpqWebdIkWJ653C0mRlFvYLDLPKETr40FjePu/YZ/EeqdPwVW7j1VEDlMzkh4w7GJg/AH8AaGaYu8YgaFufcyTRgauYtyJa5YWith89jNLKEi7uy3EpqX7hzGcxJIPDMSnwteD4nb7k4bpjyoU9JaHsaH/W2BbU1uSPbdevCbqusXV74GWGTdFYCXwt6ScFhUIrdHLS92sYcCnbtOVNC4F5yzyCTGtKHXIRIR2WCCgVDUBLF5nn/t/yEzPSqGtvFTr8B5nVZnYuRbqcp9wijojEBOoi21fm2oYahmH5Gusn6iuoOgadwiPLvOf5idTvv5KN1ZgUC6DRu8yO56FIk7yPEobYlsJYhcKjeHVo+o0kbzXjm5L1GVYdpk9x/Am1yslzJGn2X9+xYb21AXjZGOdWGZ7ocMz1PHXefMbvaU2htWNsV5JT9b+8MjyNFr090PzyGVELw/kHqiaoeQ=
  - secure: JxID0Uz75DlPH8vQedyafgEsf9jtZaC0Ma+KR/igKqcgE1zb5HhcjK8BnwyjbY3o6LfY8RbTsnnR4qMUTutC5LRT9kbVNkFw+WhTatT8pvYr750R1nzdAbd4yLpDma6sVavSEvxqt20eEk0lmDEs39yG2J9fwL3WBnSQzObksvSBsp6RrSOOdBOcwkidR3IVcvzNLml9mNoW7W+X5mzpnSv1TzNSPujzKrAHkFtQFIKfVode1ifp8rFiD7JVMfc3B2vteWCpgBooUzPxmK0jdiiiZcc36+oNpj8TOZy2tYG9E+GpZAyv8l3jF/rsqcqPppYvVtd1H4YOVzf/OqokiVznpKksQcnEg+z8N6/CvNzCi0G9f8bEIeUdTvrDp/lwWeXs9DslssAq/8wV44ztvB6DNy368E58w0cqi3p5K2YVuGT3xSxgKp4IWtr/e7nvkjZpz2ABOyDDzKFnJ6cEc/eo/Zu+TB+3cPvvve5dFBMzbVCBXlA+aWqEplxjyGrSBsOJsTd2DbYLRN1yxQtlR1B4Yh1iKYx/AB9vk+HyCOOhc0BLZhoTNIxTNXwKbFYVsSJ9TM2wFf22j13zckAF+lPfrCoEo2bJoSk1Fteotbw+emTDgrLURYKKwxukGGgreoVlW7CsBt3VNSjEE/1ulx4ROTODsAS4ZiGpjWD2Rqk=
script:
- molecule create
- molecule converge
- molecule verify
after_script:
- molecule destroy
before_install:
- openssl aes-256-cbc -K $encrypted_48923027f180_key -iv $encrypted_48923027f180_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
notifications:
  slack:
    rooms:
      secure: WdT6CCn0mHjzSyd3gjZBsIA42PzL38iQ9pEZE7nsqkzjO421DYZSOJv3+U6fZKC54yzdrI3M9mRw8jHSO4oUyeLVQ/zkD1ttry4anjB/pjXicgmXF1kfWrtJ23p3OzLATfC5k0yTrrggC+F2SI8vO6Gucoc7Fst0e1KPht+aW9TYKU0DKV6yLCAUQ+1H1sjYzkfX4IUvdB/eKvtkWwunf6j/SuzbDdzurCua8PSYIbXSJ6XQhX41h2m3gASmL8HzBQesZmD2kee7I2xi2QQRJPa3SruUpitpeFvoIzes7k/+HYN0bffmAdOzA1rpduQbITIPMH4UolNGQU3UAtMC1kI5XFTMwyHCZgqBPMURggCe35d9Gv0KWOZFBpiA+wetBOV48Dn6e+VUakmF57pkEpM0tzXnJHGjlYpbRnooPw1cGJjpHGEC/hgVzFS47XZ8u+ngXEL27CK8N8VVCOKJ7O7jNkNQPakbD3s0/KXDGAk+D/uDngib7LCFivCDWY6GqO2HmYGK09+rzZtNKePV/w/x99jAlvkdX6nlNOVUCyRzv9SaBuorCeC1HhxM/RORm5CTG8mW2wPi2ItgG7e/1W8Xy1r6/QlLoZEI68P7krYbdFcmMGO0X2YAAxWVXOL/X+emX1RnwZpwctNV2RMaV7XVXjAlhwrvEpb6CC3+foQ=
